<?php

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;

class BillDetailRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        $rule = [];
        if (!empty($this->request->get('bill_infos_fee_payment_price'))) {
            $rule += ['bill_infos_fee_payment_price' => 'numeric'];
        }

        if (!empty($this->request->get('bill_infos_fee_billing_date'))) {
            $rule += ['bill_infos_fee_billing_date' => 'date_format:Y/m/d'];
        }
        if (!empty($this->request->get('bill_infos_fee_payment_date'))) {
            $rule += ['bill_infos_fee_payment_date' => 'date_format:Y/m/d'];
        }
        return $rule;
    }

    /**
     * Message validate
     * @return array
     */
    public function messages()
    {
        return [
            'numeric' => trans('bill.numeric_error'),
            'date_format' => trans('bill.date_fomat_error')
        ];
    }

    /**
     * @param Validator $validator
     * @throws \Illuminate\Validation\ValidationException
     */
    public function failedValidation(Validator $validator)
    {
        $this->session()->flash('input_error', trans('bill.input_error'));
        $this->session()->flash('class_error', 'error');
        parent::failedValidation($validator); // Change the autogenerated stub
    }
}
