<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class PrefectureDetailRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return boolean
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'genre_id' => 'required|numeric',
            'prefecture_cd' => 'required|numeric',
            'exclusion_pattern' => 'required|numeric',
            'limit_asap' => 'required|numeric',
            'limit_immediately' => 'required|numeric',
            'asap' => 'required|numeric',
            'immediately' => 'required|numeric',
            'open_rank_a' => 'required|numeric|min:0|max:100',
            'open_rank_b' => 'required|numeric|min:0|max:100',
            'open_rank_c' => 'required|numeric|min:0|max:100',
            'open_rank_d' => 'required|numeric|min:0|max:100',
            'open_rank_z' => 'required|numeric|min:0|max:100',
            'tel_hope_a' => 'required|numeric|min:0|max:100',
            'tel_hope_b' => 'required|numeric|min:0|max:100',
            'tel_hope_c' => 'required|numeric|min:0|max:100',
            'tel_hope_d' => 'required|numeric|min:0|max:100',
            'tel_hope_z' => 'required|numeric|min:0|max:100',
            'normal3' => 'required|numeric',
        ];
    }

    /**
     * @return array
     */
    public function messages()
    {
        return parent::messages(); // Change the autogenerated stub
    }
}
