<?php

namespace App\Providers;

use App\Repositories\DemandAttachedFileRepositoryInterface;
use App\Repositories\Eloquent\AutoSelectCorpRepository;
use App\Repositories\Eloquent\DemandAttachedFileRepository;
use App\Repositories\Eloquent\MAnswerRepository;
use App\Repositories\Eloquent\MSiteGenresRepository;
use App\Repositories\Eloquent\MStaffCategoryExclusionsRepository;
use App\Repositories\Eloquent\MStaffRepository;
use App\Repositories\Eloquent\SelectGenrePrefectureRepository;
use App\Repositories\Eloquent\SelectGenreRepository;
use App\Repositories\MAnswerRepositoryInterface;
use App\Repositories\MSiteGenresRepositoryInterface;
use App\Repositories\MStaffCategoryExclusionsRepositoryInterface;
use App\Repositories\MStaffRepositoryInterface;
use App\Repositories\SelectGenrePrefectureRepositoryInterface;
use App\Repositories\SelectGenreRepositoryInterface;
use Illuminate\Support\ServiceProvider;

class RepositoryBindServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     */
    public function boot()
    {
        //
    }

    /**
     * Register any application services.
     */
    public function register()
    {
        $this->app->singleton(
            \App\Repositories\AdditionInfoRepositoryInterface::class,
            \App\Repositories\Eloquent\AdditionInfoRepository::class
        );
        $this->app->singleton(
            \App\Repositories\MItemRepositoryInterface::class,
            \App\Repositories\Eloquent\MItemRepository::class
        );
        $this->app->singleton(
            \App\Repositories\AffiliationAreaStatRepositoryInterface::class,
            \App\Repositories\Eloquent\AffiliationAreaStatRepository::class
        );
        $this->app->singleton(
            \App\Repositories\CorpAgreementTempLinkRepositoryInterface::class,
            \App\Repositories\Eloquent\CorpAgreementTempLinkRepository::class
        );
        $this->app->singleton(
            \App\Repositories\MCorpRepositoryInterface::class,
            \App\Repositories\Eloquent\MCorpRepository::class
        );
        $this->app->singleton(
            \App\Repositories\AgreementAttachedFileRepositoryInterface::class,
            \App\Repositories\Eloquent\AgreementAttachedFileRepository::class
        );
        $this->app->singleton(
            \App\Repositories\AntisocialCheckRepositoryInterface::class,
            \App\Repositories\Eloquent\AntisocialCheckRepository::class
        );
        $this->app->singleton(
            \App\Repositories\MCorpCategoryRepositoryInterface::class,
            \App\Repositories\Eloquent\MCorpCategoryRepository::class
        );
        $this->app->singleton(
            \App\Repositories\AutoCommissionCorpRepositoryInterface::class,
            \App\Repositories\Eloquent\AutoCommissionCorpRepository::class
        );
        $this->app->singleton(
            \App\Repositories\MTargetAreaRepositoryInterface::class,
            \App\Repositories\Eloquent\MTargetAreaRepository::class
        );
        $this->app->singleton(
            \App\Repositories\MCorpCategoriesTempRepositoryInterface::class,
            \App\Repositories\Eloquent\MCorpCategoriesTempRepository::class
        );
        $this->app->singleton(
            \App\Repositories\MCategoryRepositoryInterface::class,
            \App\Repositories\Eloquent\MCategoryRepository::class
        );
        $this->app->singleton(
            \App\Repositories\MCorpTargetAreaRepositoryInterface::class,
            \App\Repositories\Eloquent\MCorpTargetAreaRepository::class
        );
        $this->app->singleton(
            \App\Repositories\AgreementRepositoryInterface::class,
            \App\Repositories\Eloquent\AgreementRepository::class
        );
        $this->app->singleton(
            \App\Repositories\MGenresRepositoryInterface::class,
            \App\Repositories\Eloquent\MGenresRepository::class
        );
        $this->app->singleton(
            \App\Repositories\AffiliationInfoRepositoryInterface::class,
            \App\Repositories\Eloquent\AffiliationInfoRepository::class
        );
        $this->app->singleton(
            \App\Repositories\CommissionInfoRepositoryInterface::class,
            \App\Repositories\Eloquent\CommissionInfoRepository::class
        );
        $this->app->singleton(
            \App\Repositories\CommissionTelSupportRepositoryInterface::class,
            \App\Repositories\Eloquent\CommissionTelSupportRepository::class
        );
        $this->app->singleton(
            \App\Repositories\CommissionVisitSupportRepositoryInterface::class,
            \App\Repositories\Eloquent\CommissionVisitSupportRepository::class
        );
        $this->app->singleton(
            \App\Repositories\CommissionOrderSupportRepositoryInterface::class,
            \App\Repositories\Eloquent\CommissionOrderSupportRepository::class
        );
        $this->app->singleton(
            \App\Repositories\MCorpSubRepositoryInterface::class,
            \App\Repositories\Eloquent\MCorpSubRepository::class
        );
        $this->app->singleton(
            \App\Repositories\MCorpNewYearRepositoryInterface::class,
            \App\Repositories\Eloquent\MCorpNewYearRepository::class
        );
        $this->app->singleton(
            \App\Repositories\ProgDemandInfoRepositoryInterface::class,
            \App\Repositories\Eloquent\ProgDemandInfoRepository::class
        );
        $this->app->singleton(
            \App\Repositories\ProgCorpRepositoryInterface::class,
            \App\Repositories\Eloquent\ProgCorpRepository::class
        );
        $this->app->singleton(
            \App\Repositories\DemandInfoRepositoryInterface::class,
            \App\Repositories\Eloquent\DemandInfoRepository::class
        );
        $this->app->singleton(
            \App\Repositories\MSiteRepositoryInterface::class,
            \App\Repositories\Eloquent\MSiteRepository::class
        );
        $this->app->singleton(
            \App\Repositories\AutoCallRepositoryInterface::class,
            \App\Repositories\Eloquent\AutoCallRepository::class
        );
        $this->app->singleton(
            \App\Repositories\MPostRepositoryInterface::class,
            \App\Repositories\Eloquent\MPostRepository::class
        );
        $this->app->singleton(
            \App\Repositories\AgreementStatusHistoryRepositoryInterface::class,
            \App\Repositories\Eloquent\AgreementStatusHistoryRepository::class
        );
        $this->app->singleton(
            \App\Repositories\ProgImportFilesRepositoryInterface::class,
            \App\Repositories\Eloquent\ProgImportFilesRepository::class
        );
        $this->app->singleton(
            \App\Repositories\AgreementEditHistoryRepositoryInterface::class,
            \App\Repositories\Eloquent\AgreementEditHistoryRepository::class
        );
        $this->app->singleton(
            \App\Repositories\AgreementCustomizeRepositoryInterface::class,
            \App\Repositories\Eloquent\AgreementCustomizeRepository::class
        );
        $this->app->singleton(
            \App\Repositories\CommissionCorrespondsRepositoryInterface::class,
            \App\Repositories\Eloquent\CommissionCorrespondsRepository::class
        );
        $this->app->singleton(
            \App\Repositories\MoneyCorrespondRepositoryInterface::class,
            \App\Repositories\Eloquent\MoneyCorrespondRepository::class
        );
        $this->app->singleton(
            \App\Repositories\BillRepositoryInterface::class,
            \App\Repositories\Eloquent\BillRepository::class
        );
        $this->app->singleton(
            \App\Repositories\AuctionInfoRepositoryInterface::class,
            \App\Repositories\Eloquent\AuctionInfoRepository::class
        );
        $this->app->singleton(
            \App\Repositories\MTimeRepositoryInterface::class,
            \App\Repositories\Eloquent\MTimeRepository::class
        );
        $this->app->singleton(
            \App\Repositories\PublicHolidayRepositoryInterface::class,
            \App\Repositories\Eloquent\PublicHolidayRepository::class
        );
        $this->app->singleton(
            \App\Repositories\AuctionGenreRepositoryInterface::class,
            \App\Repositories\Eloquent\AuctionGenreRepository::class
        );
        $this->app->singleton(
            \App\Repositories\ExclusionTimeRepositoryInterface::class,
            \App\Repositories\Eloquent\ExclusionTimeRepository::class
        );
        $this->app->singleton(
            \App\Repositories\NoticeInfoRepositoryInterface::class,
            \App\Repositories\Eloquent\NoticeInfoRepository::class
        );
        $this->app->singleton(
            \App\Repositories\MCorpsNoticeInfoRepositoryInterface::class,
            \App\Repositories\Eloquent\MCorpsNoticeInfoRepository::class
        );
        $this->app->singleton(
            \App\Repositories\RefusalsRepositoryInterface::class,
            \App\Repositories\Eloquent\RefusalsRepository::class
        );
        $this->app->singleton(
            \App\Repositories\AccumulatedInformationsRepositoryInterface::class,
            \App\Repositories\Eloquent\AccumulatedInformationsRepository::class
        );
        $this->app->singleton(
            \App\Repositories\AgreementProvisionsRepositoryInterface::class,
            \App\Repositories\Eloquent\AgreementProvisionsRepository::class
        );
        $this->app->singleton(
            \App\Repositories\MGeneralSearchRepositoryInterface::class,
            \App\Repositories\Eloquent\MGeneralSearchRepository::class
        );
        $this->app->singleton(
            \App\Repositories\AffiliationSubsRepositoryInterface::class,
            \App\Repositories\Eloquent\AffiliationSubsRepository::class
        );
        $this->app->singleton(
            \App\Repositories\AffiliationStatsRepositoryInterface::class,
            \App\Repositories\Eloquent\AffiliationStatsRepository::class
        );
        $this->app->singleton(
            \App\Repositories\AffiliationCorrespondsRepositoryInterface::class,
            \App\Repositories\Eloquent\AffiliationCorrespondsRepository::class
        );
        $this->app->singleton(
            \App\Repositories\ReputationCheckRepositoryInterface::class,
            \App\Repositories\Eloquent\ReputationCheckRepository::class
        );
        $this->app->singleton(
            \App\Repositories\NoticeInfoTargetRepositoryInterface::class,
            \App\Repositories\Eloquent\NoticeInfoTargetRepository::class
        );
        $this->app->singleton(
            \App\Repositories\VisitTimeRepositoryInterface::class,
            \App\Repositories\Eloquent\VisitTimeRepository::class
        );
        $this->app->singleton(
            \App\Repositories\GeneralSearchItemRepositoryInterface::class,
            \App\Repositories\Eloquent\GeneralSearchItemRepository::class
        );
        $this->app->singleton(
            \App\Repositories\GeneralSearchConditionRepositoryInterface::class,
            \App\Repositories\Eloquent\GeneralSearchConditionRepository::class
        );
        $this->app->singleton(
            \App\Repositories\MUserRepositoryInterface::class,
            \App\Repositories\Eloquent\MUserRepository::class
        );
        $this->app->singleton(
            \App\Repositories\DemandCorrespondsRepositoryInterface::class,
            \App\Repositories\Eloquent\DemandCorrespondsRepository::class
        );
        $this->app->singleton(
            \App\Repositories\AgreementProvisionsEditLogRepositoryInterface::class,
            \App\Repositories\Eloquent\AgreementProvisionsEditLogRepository::class
        );
        $this->app->singleton(
            \App\Repositories\AgreementRevisionLogRepositoryInterface::class,
            \App\Repositories\Eloquent\AgreementRevisionLogRepository::class
        );
        $this->app->singleton(
            \App\Repositories\AgreementProvisionsItemRepositoryInterface::class,
            \App\Repositories\Eloquent\AgreementProvisionsItemRepository::class
        );
        $this->app->singleton(
            \App\Repositories\NotCorrespondRepositoryInterface::class,
            \App\Repositories\Eloquent\NotCorrespondRepository::class
        );
        $this->app->singleton(
            \App\Repositories\AgreementAdminCategoryRepositoryInterface::class,
            \App\Repositories\Eloquent\AgreementAdminCategoryRepository::class
        );
        $this->app->singleton(
            \App\Repositories\DemandInquiryAnsRepositoryInterface::class,
            \App\Repositories\Eloquent\DemandInquiryAnsRepository::class
        );
        $this->app->singleton(
            \App\Repositories\MAddress1RepositoryInterface::class,
            \App\Repositories\Eloquent\MAddress1Repository::class
        );
        $this->app->singleton(
            \App\Repositories\CorpAgreementRepositoryInterface::class,
            \App\Repositories\Eloquent\CorpAgreementRepository::class
        );
        $this->app->singleton(
            \App\Repositories\AuctionGenreAreaRepositoryInterface::class,
            \App\Repositories\Eloquent\AuctionGenreAreaRepository::class
        );
        $this->app->singleton(
            \App\Repositories\ProgAddDemandInfoRepositoryInterface::class,
            \App\Repositories\Eloquent\ProgAddDemandInfoRepository::class
        );
        $this->app->singleton(
            \App\Repositories\ProgItemRepositoryInterface::class,
            \App\Repositories\Eloquent\ProgItemRepository::class
        );
        $this->app->singleton(
            \App\Repositories\MCategoryCopyRuleRepositoryInterface::class,
            \App\Repositories\Eloquent\MCategoryCopyRuleRepository::class
        );
        $this->app->singleton(
            MSiteGenresRepositoryInterface::class,
            MSiteGenresRepository::class
        );

        $this->app->singleton(
            SelectGenrePrefectureRepositoryInterface::class,
            SelectGenrePrefectureRepository::class
        );

        $this->app->singleton(
            SelectGenreRepositoryInterface::class,
            SelectGenreRepository::class
        );

        $this->app->singleton(
            DemandAttachedFileRepositoryInterface::class,
            DemandAttachedFileRepository::class
        );
        $this->app->singleton(
            \App\Repositories\ApprovalRepositoryInterface::class,
            \App\Repositories\Eloquent\ApprovalRepository::class
        );
        $this->app->singleton(
            \App\Repositories\CommissionAppRepositoryInterface::class,
            \App\Repositories\Eloquent\CommissionAppRepository::class
        );
        $this->app->singleton(
            \App\Repositories\MTaxRateRepositoryInterface::class,
            \App\Repositories\Eloquent\MTaxRateRepository::class
        );
        $this->app->singleton(
            \App\Repositories\MCommissionTypeRepositoryInterface::class,
            \App\Repositories\Eloquent\MCommissionTypeRepository::class
        );
        $this->app->singleton(
            \App\Repositories\AgreementAdminLicenseRepositoryInterface::class,
            \App\Repositories\Eloquent\AgreementAdminLicenseRepository::class
        );
        $this->app->singleton(
            \App\Repositories\ProgAddDemandInfoRepositoryInterface::class,
            \App\Repositories\Eloquent\ProgAddDemandInfoRepository::class
        );
        $this->app->singleton(
            \App\Repositories\AuctionRankingRepoInterface::class,
            \App\Repositories\Eloquent\AuctionRankingRepository::class
        );
        $this->app->singleton(
            \App\Repositories\CorpCategoryGroupApplicationRepositoryInterface::class,
            \App\Repositories\Eloquent\CorpCategoryGroupApplicationRepository::class
        );
        $this->app->singleton(
            \App\Repositories\NotCorrespondItemRepositoryInterface::class,
            \App\Repositories\Eloquent\NotCorrespondItemRepository::class
        );
        $this->app->singleton(
            \App\Repositories\ProgDemandInfoLogRepositoryInterface::class,
            \App\Repositories\Eloquent\ProgDemandInfoLogRepository::class
        );
        $this->app->singleton(
            \App\Repositories\ProgAddDemandInfoLogRepositoryInterface::class,
            \App\Repositories\Eloquent\ProgAddDemandInfoLogRepository::class
        );
        $this->app->singleton(
            \App\Repositories\DemandAttachedFileRepositoryInterface::class,
            \App\Repositories\Eloquent\DemandAttachedFileRepository::class
        );
        $this->app->singleton(
            \App\Repositories\MCommissionAlertSettingRepositoryInterface::class,
            \App\Repositories\Eloquent\MCommissionAlertSettingRepository::class
        );
        $this->app->singleton(
            \App\Repositories\SelectionGenreRepositoryInterface::class,
            \App\Repositories\Eloquent\SelectionGenreRepository::class
        );
        $this->app->singleton(
            \App\Repositories\SelectionGenrePrefectureRepositoryInterface::class,
            \App\Repositories\Eloquent\SelectionGenrePrefectureRepository::class
        );
        $this->app->singleton(
            \App\Repositories\CorpCategoryApplicationRepositoryInterface::class,
            \App\Repositories\Eloquent\CorpCategoryApplicationRepository::class
        );
        $this->app->singleton(
            \App\Repositories\NotCorrespondLogRepositoryInterface::class,
            \App\Repositories\Eloquent\NotCorrespondLogRepository::class
        );
        $this->app->singleton(
            \App\Repositories\ProgDemandInfoTmpRepositoryInterface::class,
            \App\Repositories\Eloquent\ProgDemandInfoTmpRepository::class
        );
        $this->app->singleton(
            \App\Repositories\ProgAddDemandInfoTmpRepositoryInterface::class,
            \App\Repositories\Eloquent\ProgAddDemandInfoTmpRepository::class
        );
        $this->app->singleton(
            \App\Repositories\ProgDemandInfoOtherTmpRepositoryInterface::class,
            \App\Repositories\Eloquent\ProgDemandInfoOtherTmpRepository::class
        );
        $this->app->singleton(
            MAnswerRepositoryInterface::class,
            MAnswerRepository::class
        );
        $this->app->singleton(
            \App\Repositories\DeviceInfoRepositoryInterface::class,
            \App\Repositories\Eloquent\DeviceInfoRepository::class
        );
        $this->app->singleton(
            \App\Repositories\MSiteCategoryRepositoryInterface::class,
            \App\Repositories\Eloquent\MSiteCategoryRepository::class
        );
        $this->app->singleton(
            \App\Repositories\MInquiryRepositoryInterface::class,
            \App\Repositories\Eloquent\MInquiryRepository::class
        );
        $this->app->singleton(
            \App\Repositories\CategoryLicenseLinkRepositoryInterface::class,
            \App\Repositories\Eloquent\CategoryLicenseLinkRepository::class
        );
        $this->app->singleton(
            \App\Repositories\CyzenDemandInfoRepositoryInterface::class,
            \App\Repositories\Eloquent\CyzenDemandInfoRepository::class
        );
        $this->app->singleton(
            \App\Repositories\WeatherRepositoryInterface::class,
            \App\Repositories\Eloquent\WeatherRepository::class
        );
        $this->app->singleton(
            \App\Repositories\WeatherForecastRepositoryInterface::class,
            \App\Repositories\Eloquent\WeatherForecastRepository::class
        );
        $this->app->singleton(
            \App\Repositories\DemandForecastRepositoryInterface::class,
            \App\Repositories\Eloquent\DemandForecastRepository::class
        );
        $this->app->singleton(
            \App\Repositories\DemandActualRepositoryInterface::class,
            \App\Repositories\Eloquent\DemandActualRepository::class
        );
        $this->app->singleton(
            \App\Repositories\PgDescriptionRepositoryInterface::class,
            \App\Repositories\Eloquent\PgDescriptionRepository::class
        );
        $this->app->singleton(
            \App\Repositories\CyzenUserRepositoryInterface::class,
            \App\Repositories\Eloquent\CyzenUserRepository::class
        );
        $this->app->singleton(
            \App\Repositories\CyzenUserGroupRepositoryInterface::class,
            \App\Repositories\Eloquent\CyzenUserGroupRepository::class
        );
        $this->app->singleton(
            \App\Repositories\CyzenGroupRepositoryInterface::class,
            \App\Repositories\Eloquent\CyzenGroupRepository::class
        );
        $this->app->singleton(
            \App\Repositories\CyzenSpotRepositoryInterface::class,
            \App\Repositories\Eloquent\CyzenSpotRepository::class
        );
        $this->app->singleton(
            \App\Repositories\CyzenSpotTagRepositoryInterface::class,
            \App\Repositories\Eloquent\CyzenSpotTagRepository::class
        );
        $this->app->singleton(
            \App\Repositories\CyzenSchedulesRepositoryInterface::class,
            \App\Repositories\Eloquent\CyzenSchedulesRepository::class
        );
        $this->app->singleton(
            \App\Repositories\CyzenTrackingRepositoryInterface::class,
            \App\Repositories\Eloquent\CyzenTrackingRepository::class
        );
        $this->app->singleton(
            \App\Repositories\CyzenHistoryRepositoryInterface::class,
            \App\Repositories\Eloquent\CyzenHistoryRepository::class
        );
        $this->app->singleton(
            \App\Repositories\CyzenStatusRepositoryInterface::class,
            \App\Repositories\Eloquent\CyzenStatusRepository::class
        );
        $this->app->singleton(
            \App\Repositories\DemandNotificationRepositoryInterface::class,
            \App\Repositories\Eloquent\DemandNotificationRepository::class
        );
        $this->app->singleton(
            \App\Repositories\CorpLicenseLinkRepositoryInterface::class,
            \App\Repositories\Eloquent\CorpLicenseLinkRepository::class
        );
        $this->app->singleton(
            \App\Repositories\DemandExtendInfoRepositoryInterface::class,
            \App\Repositories\Eloquent\DemandExtendInfoRepository::class
        );
        $this->app->singleton(
            \App\Repositories\FiltersRepositoryInterface::class,
            \App\Repositories\Eloquent\FiltersRepository::class
        );
        $this->app->singleton(
            \App\Repositories\FiltersConditionsRepositoryInterface::class,
            \App\Repositories\Eloquent\FiltersConditionsRepository::class
        );
        $this->app->singleton(
            \App\Repositories\CorpRegisteredScheduleRepositoryInterface::class,
            \App\Repositories\Eloquent\CorpRegisteredScheduleRepository::class
        );
        $this->app->singleton(
            MStaffCategoryExclusionsRepositoryInterface::class,
            MStaffCategoryExclusionsRepository::class
        );
        $this->app->singleton(
            MStaffRepositoryInterface::class,
            MStaffRepository::class
        );
    }
}
